image: php:7.2

stages:
  - deploy

before_script: 
  - apt-get update -qq
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - apt-get -y install rsync
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan 45.79.0.55 >> ~/.ssh/authorized_keys
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - chmod 644 ~/.ssh
  
stage_deploy:
  only:
    refs:
      - development
  stage: deploy
  script:
    # Sync specific file formats from the repository to the server.
    #   .php:       most of what the game is coded in
    #   .js:        node scripts and/or included js files
    #   .json:      package.json & map.json files
    #   .scss/.css: layout system
    - rsync -azhP --no-perms --filter=':- .gitignore' --include='*/' --include='*.'{php,js,css,scss,png,tmx,sh} --exclude='*' ./ gitlab@45.79.0.55:/var/www/html/absoluterpg.com/public_html/