image: php:7.2

stages:
  - deploy

stage_deploy:
  only:
    refs:
      - ci-cd-pipeline-config-test
  stage: deploy
  script:
    - echo "Hello, $GITLAB_USER_LOGIN"
    - echo "Deploying from the $CI_COMMIT_BRANCH branch with a hash of $CI_COMMIT_SHA"