version: '3'

services:
    web:
        container_name: absolute-web
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/nginx/ssl
            - ./app:/app
            - ./logs:/logs
        depends_on:
            - mysql
        networks:
            - absolute


    mysql:
        container_name: absolute-mysql
        image: mariadb:latest
        volumes:
            - absolute-mysqldata:/var/lib/mysql
            - ./migrations/sql:/data/application/sql
            - ./migrations/migrate.sh:/data/application/migrate.sh
            - ./.env:/data/application/.env
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-file /data/application/migrate.sh
        ports:
            - 3306:3306
        networks:
            - absolute


    phpmyadmin:
        container_name: absolute-phpmyadmin
        image: phpmyadmin:latest
        environment:
            PMA_HOST: mysql
            PMA_ABSOLUTE_URI: '/db/'
            UPLOAD_LIMIT: 512M
        ports:
            - 8080:80
        depends_on:
            - mysql
        networks:
            - absolute


    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        networks:
            - absolute


    php:
        container_name: absolute-php
        build:
            context: .
            dockerfile: dockerfiles/absolute.dockerfile
        env_file:
            - .env
        volumes:
            - ./app:/app
            - ./logs:/logs
            - ./migrations:/migrations:ro
            - ./config/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
            - ./config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./config/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - mysql
        networks:
            - absolute


    themes:
        container_name: absolute-themes
        build:
            context: .
            dockerfile: dockerfiles/themes.dockerfile
        volumes:
            - ./app/themes:/app/themes
        depends_on:
            - mysql
        networks:
            - absolute


    discord:
        container_name: absolute-discord
        restart: on-failure
        init: true
        build:
            context: .
            dockerfile: dockerfiles/discord.dockerfile
        volumes:
            - ./absolute/discord:/app/discord
        ports:
            - 3000:3306
        depends_on:
            - mysql
        networks:
            - absolute


volumes:
    absolute-mysqldata: {}

networks:
    absolute:
        name: absolute
