services:
    ecrpg-nginx:
        container_name: ecrpg-nginx
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/nginx/ssl
            - ./app:/app
            - ./logs:/logs
            - chat-build:/app/js/chat
        depends_on:
            - ecrpg-mysql # Updated dependency
            - ecrpg-chat  # Updated dependency
        networks:
            - ecrpg-network # Updated network


    ecrpg-mysql:
        container_name: ecrpg-mysql
        image: mariadb:10.7
        env_file:
            - .env
        environment:
            MARIADB_AUTO_UPGRADE: 1
        volumes:
            - ecrpg-mysqldata:/var/lib/mysql # Updated volume
            - ./.env:/data/application/.env
            - ./config/my.cnf:/etc/mysql/my.cnf
            - ./migrations/sql:/data/application/sql
            - ./migrations/migrate.sh:/data/application/migrate.sh
            - ./logs/mysql_errors.log:/var/log/mysql/error.log
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - 3307:3306
        networks:
            - ecrpg-network # Updated network


    ecrpg-phpmyadmin:
        container_name: ecrpg-phpmyadmin
        image: phpmyadmin:latest
        environment:
            PMA_HOST: ecrpg-mysql # Updated PMA_HOST
            PMA_ABSOLUTE_URI: '/db/'
            UPLOAD_LIMIT: 512M
        depends_on:
            - ecrpg-mysql # Updated dependency
        networks:
            - ecrpg-network # Updated network


    ecrpg-certbot: # Renamed for consistency
        container_name: ecrpg-certbot
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        networks:
            - ecrpg-network # Updated network


    ecrpg-php-fpm: # Renamed for clarity and consistency
        container_name: ecrpg-php-fpm
        build:
            context: .
            dockerfile: dockerfiles/absolute.dockerfile # Dockerfile name might also need update later
        env_file:
            - .env
        volumes:
            - ./app:/app
            - ./logs:/logs
            - ./migrations:/migrations:ro
            - ./config/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
            - ./config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./config/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - ecrpg-mysql # Updated dependency
        networks:
            - ecrpg-network # Updated network


    ecrpg-discord:
        container_name: ecrpg-discord
        restart: on-failure
        init: true
        build:
            context: .
            dockerfile: dockerfiles/discord.dockerfile # Dockerfile name might also need update later
        volumes:
            - ./absolute/discord:/app/discord # Path to submodule - keep as is unless submodule dir name changed
        ports:
            - 3000:3000
        depends_on:
            - ecrpg-mysql # Updated dependency
        networks:
            - ecrpg-network # Updated network

    ecrpg-chat:
        container_name: ecrpg-chat
        restart: on-failure
        init: true
        build:
            context: .
            dockerfile: dockerfiles/chat.dockerfile # Dockerfile name might also need update later
        volumes:
            - chat-build:/chat/build/client
        ports:
            - 8080:8080
        depends_on:
            - ecrpg-mysql # Updated dependency
        networks:
            - ecrpg-network # Updated network


volumes:
    ecrpg-mysqldata: {} # Updated volume name
    chat-build: {}

networks:
    ecrpg-network: # Updated network name
        name: ecrpg-network # Explicitly name the network
        driver: bridge
